const productsData = {
    newProducts: [{

            id: 1,
            name: "Sandal Cao Gót DL0565",
            image: "../image/sanpham1.png",
            price: 349000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Sandal Cao Gót DL0547",
            image: "../image/sp2.png",
            price: 379000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Dép Classic Lined Clog",
            image: "../image/sp3.png",
            price: 799000,
            decrease: 399000,
            discount: "-33%",
        },
        {
            id: 4,
            name: "Sandal Cao Gót DL0548",
            image: "../image/sp4.png",
            price: 369000,
            promotion: "new",
        },

        {
            id: 5,
            name: "Sandal Cao Gót DL0549",
            image: "../image/sp5.png",
            price: 289000,
            promotion: "new",
        },
        {
            id: 6,
            name: "Sandal Đế Đúp DL0546",
            image: "../image/sp6.png",
            price: 490000,
            decrease: 329000,
            discount: "-21%",
        },
        {
            id: 7,
            name: "Sandal Cao Gót DL0534",
            image: "../image/sp7.png",
            price: 389000,
            decrease: 299000,
            discount: "-20%",
        },
        {
            id: 8,
            name: "Sandal Cao Gót DL0548",
            image: "../image/sp8.png",
            price: 499999,
            decrease: 399999,
            discount: "-10%",
        },
    ],
    sandal: [{

        id: 1,
        name: "Sandal Cao Gót DL0565",
        image: "../image/sanpham1.png",
        price: 349000,
        promotion: "new",
    },
    {
        id: 2,
        name: "Sandal Cao Gót DL0547",
        image: "../image/sp2.png",
        price: 379000,
        promotion: "new",
    },
    {
        id: 3,
        name: "Dép Classic Lined Clog",
        image: "../image/sp3.png",
        price: 799000,
        decrease: 399000,
        discount: "-33%",
    },
    {
        id: 4,
        name: "Sandal Cao Gót DL0548",
        image: "../image/sp4.png",
        price: 369000,
        promotion: "new",
    },

    {
        id: 5,
        name: "Sandal Cao Gót DL0549",
        image: "../image/sp5.png",
        price: 289000,
        promotion: "new",
    },
    {
        id: 6,
        name: "Sandal Đế Đúp DL0546",
        image: "../image/sp6.png",
        price: 490000,
        decrease: 329000,
        discount: "-21%",
    },
    {
        id: 7,
        name: "Sandal Cao Gót DL0534",
        image: "../image/sp16.png",
        price: 389000,
        decrease: 299000,
        discount: "-20%",
    },
    {
        id: 8,
        name: "Sandal Cao Gót DL0548",
        image: "../image/sp8.png",
        price: 499999,
        decrease: 399999,
        discount: "-10%",
    },
    {
        id: 9,
        name: "Guốc Đế Xuồng DL0537",
        image: "../image/sp10.png",
        price: 7200000,
        promotion: "new",
    },
    ],
    depguoc: [{
            id: 1,
            name: "Guốc Sục DL0556",
            image: "../image/sp9.png",
            price: 419000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Dép Guốc DL0542",
            image: "../image/sp10.png",
            price: 369000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Guốc Đế Xuồng DL0537",
            image: "../image/sp10.png",
            price: 7200000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Dép Guốc DL0538",
            image: "../image/sp11.png",
            price: 312000,
            promotion: "new",
        },
        {
            id: 5,
            name: "Dép Bệt DL0528",
            image: "../image/sp12.png",
            price: 329000,
            decrease: 229000,
            discount: "-33%",
        },
        {
            id: 6,
            name: "Dép Guốc DL0527",
            image: "../image/sp13.png",
            price: 450000,
            decrease: 400000,
            discount: "-10%",
        },
        {
            id: 7,
            name: "Dép Bánh Mì AG0162",
            image: "../image/sp14.png",
            price: 290000,
        },
        {
            id: 8,
            name: "Guốc Sục DL0539 ",
            image: "../image/sp15.png",
            price: 550000,
        },

    ],
    giaycaogot: [{
        id: 1,
        name: "Giày Slingback DL0560",
        image: "../image/sp17.png",
        price: 419000,
        promotion: "new",
    },
    {
        id: 2,
        name: "Giày Bít DL0557",
        image: "../image/sp18.png",
        price: 369000,
        promotion: "new",
    },
    {
        id: 3,
        name: "Giày Slingback DL0558",
        image: "../image/sp19.png",
        price: 172000,
        promotion: "new",
    },
    {
        id: 4,
        name: "Giày Bít DL0555",
        image: "../image/sp20.png",
        price: 320000,
        promotion: "new",
    },
    {
        id: 5,
        name: "Giày Slingback DL0554",
        image: "../image/sp21.png",
        price: 329000,
        decrease: 229000,
        discount: "-33%",
    },
    {
        id: 6,
        name: "Giày Bít DL0552",
        image: "../image/sp22.png",
        price: 479000,
        decrease: 420000,
        discount: "-10%",
    },
    {
        id: 7,
        name: "Giày Bít DL0553",
        image: "../image/sp23.png",
        price: 290000,
    },
    {
        id: 8,
        name: "Giày Bít DL0545",
        image: "../image/sp24.png",
        price: 350000,
    },

],

    giaybupbe: [{
        id: 1,
        name: "Giày Búp Bê DL0559",
        image: "../image/sp25.png",
        price: 319000,
        promotion: "new",
    },
    {
        id: 2,
        name: "Giày Búp Bê AA0439",
        image: "../image/sp26.png",
        price: 369000,
        promotion: "new",
    },
    {
        id: 3,
        name: "Giày Búp Bê AA0470",
        image: "../image/sp27.png",
        price: 172000,
        promotion: "new",
    },
    {
        id: 4,
        name: "Giày Búp Bê AA0438",
        image: "../image/sp28.png",
        price: 320000,
        promotion: "new",
    },
    {
        id: 5,
        name: "Giày Búp Bê AA0477",
        image: "../image/sp29.png",
        price: 329000,
        decrease: 229000,
        discount: "-33%",
    },
    {
        id: 6,
        name: "Giày Búp Bê AA0493",
        image: "../image/sp30.png",
        price: 479000,
        decrease: 420000,
        discount: "-10%",
    },
    {
        id: 7,
        name: "Giày Búp Bê AA0502",
        image: "../image/sp31.png",
        price: 290000,
    },
    {
        id: 8,
        name: "Giày Búp Bê AA0489",
        image: "../image/sp32.png",
        price: 350000,
    },
],
};
const productsData2 = {
    newProducts: [{
        id: 1,
        name: "Giày Slingback DL0560",
        image: "../image/sp17.png",
        price: 419000,
        promotion: "new",
    },
    {
        id: 2,
        name: "Giày Bít DL0557",
        image: "../image/sp18.png",
        price: 369000,
        promotion: "new",
    },
    {
        id: 3,
        name: "Giày Slingback DL0558",
        image: "../image/sp19.png",
        price: 172000,
        promotion: "new",
    },
    {
        id: 4,
        name: "Giày Bít DL0555",
        image: "../image/sp20.png",
        price: 320000,
        promotion: "new",
    },
    ],
    popularProduct: [
        {
            id: 6,
            name: "Dép Guốc DL0527",
            image: "../image/sp13.png",
            price: 450000,
            decrease: 400000,
            discount: "-10%",
        },
        {
            id: 7,
            name: "Dép Bánh Mì AG0162",
            image: "../image/sp14.png",
            price: 290000,
        },
        {
            id: 8,
            name: "Guốc Sục DL0539 ",
            image: "../image/sp15.png",
            price: 550000,
        },
    ],
    discountProduct: [{
        id: 1,
        name: "Sandal Cao Gót DL0565",
        image: "../image/sanpham1.png",
        price: 799000,
        decrease: 399000,
    },
    {
        id: 2,
        name: "Sandal Cao Gót DL0547",
        image: "../image/sp2.png",
        price: 899000,
        decrease: 399000,
    },
    {
        id: 3,
        name: "Dép Classic Lined Clog",
        image: "../image/sp3.png",
        price: 799000,
        decrease: 299000,
        discount: "-33%",
    },
    {
        id: 4,
        name: "Sandal Cao Gót DL0548",
        image: "../image/sp4.png",
        price: 709000,
        decrease: 399000,
    },
    ],
};